#!/usr/bin/python2.7
import subprocess as sp
import time
import sys
import os
import serial
import argparse

args = argparse.ArgumentParser(description='Navi the safety light service')
args.add_argument('--user', default='root')
args.add_argument('--serial_dev', default='/dev/ttyUSB0')
args = args.parse_args()
print args

# assumes user has working val_indigo workspace
user = args.user
home = '/root' if user == 'root' else '/home/'+user+''
arduino_path = args.serial_dev

echo_cmd = "PYTHONPATH=${PYTHONPATH}:" + \
		home+"/val_indigo/install/lib/python2.7/dist-packages:" + \
		"/opt/nasa/indigo/lib/python2.7/dist-packages:" + \
		"/opt/ros/indigo/lib/python2.7/dist-packages " + \
		home+"/val_indigo/src/shared_memory_transport/scripts/smttopic echo /power/pdbmti/HV_State"

with serial.Serial(arduino_path, 9600) as arduino, open('/dev/null', 'w') as devnull:
	while True:
		sp.Popen([echo_cmd], shell=True, stdout=arduino.fd, stderr=devnull).wait()
		#sp.Popen(["tail -F /home/"+user+"/test"], shell=True, stdout=arduino.fd, stderr=devnull).wait() # for debugging only
		time.sleep(3)
