#!/usr/bin/env python
import serial
import sys

with serial.Serial('/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AI03RLDW-if00-port0', 9600) as ser:
  if len(sys.argv) == 1:
    print 'need to specify on or off'
    exit(1)
  if sys.argv[1] == 'on':
    ser.write('4\n')
    print 'turning navi on'
  elif sys.argv[1] == 'off':
    ser.write('11\n')
    print 'turning navi off'
  else:
    print 'valid arguments are on or off'
